AWSTemplateFormatVersion: '2010-09-09'
Description: 'Stack 2 - Configuracion de AWS CodeDeploy'

Parameters:
  ProjectName:
    Type: String
    Default: codedeploy-demo
  EC2InstanceId:
    Type: String

Resources:
  CodeDeployRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2010-10-07'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ codedeploy.amazonaws.com ]
            Action: [ 'sts:AssumeRole' ]
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole'

  CodeDeployApplication:
    Type: 'AWS::CodeDeploy::Application'
    Properties:
      ApplicationName: !Sub '${ProjectName}-app'
      ComputePlatform: Server

  CodeDeployDeploymentGroup:
    Type: 'AWS::CodeDeploy::DeploymentGroup'
    Properties:
      ApplicationName: !Ref CodeDeployApplication
      DeploymentGroupName: !Sub '${ProjectName}-dg'
      ServiceRoleArn: !GetAtt CodeDeployRole.Arn
      DeploymentConfigName: CodeDeployDefault.AllAtOnce
      Ec2TagFilters:
        - Key: Name
          Value: !Sub '${ProjectName}-server'
          Type: KEY_AND_VALUE
      AutoRollbackConfiguration:
        Enabled: true
        Events:
          - DEPLOYMENT_FAILURE

Outputs:
  ApplicationName:
    Value: !Ref CodeDeployApplication
  DeploymentGroupName:
    Value: !Ref CodeDeployDeploymentGroup